### PR TITLE
Carlhiggs gtfs frequency patch 1

### PR DESCRIPTION
**Pull request by carlhiggs**
Amendments to the GTFS analysis algorithm and configurations were made to allow for a priori stop_times.txt cleaning to within city bounding box, due to apparent bugs in the UrbanAccess validation (unclear what these relate to; no time to fix on that end right now really).  In any case, with these amendments (as per Basecamp post [here](https://3.basecamp.com/3662734/buckets/11779922/messages/2940636017)) the Swiss and Danish national feeds are able to correctly be loaded and subset of appropriate stops for Bern and Odense respectively identified.  The setting of validation=False was found to have impacts for all cities (on number of stops identified, and percent meeting criteria), despite a priori truncation of stop_times.txt to the study region bounds. Given doubts around the UrbanAccess validation process, I have set validation=False for all regions in the configuration file now (ie. with a priori stop_times truncation).

### CODE REVIEW

**Comment by gboeing** [comment]
Thanks @carlhiggs! I see the diff says this PR is changing `+2,444,647` lines. Seems like something must be wrong... does the PR include the data files themselves, or binary files such as images (or even images inline in notebooks)? If so we'll want to remove them (and strip them out of the commit history) or we will drastically balloon the repo size. Best to reserve big files for cloudstor.

**Comment by gboeing** [comment]
Ah I see them here, looking at the per-file diff... some introduced several MB of binary changes and others introduced several hundreds of thousands of millions of lines. Probably should strip out all the input data folder contents (and their commit history) and move to cloudstor.

shot

**Comment by carlhiggs** [comment]
Hi Geoff,
Sorry the data files weren't meant to be included; I'm not sure how they
were (I didn't think they were added??).  The only files that I edited were
gtfs configuration and the analysis code - I aimed to upload the feeds to
cloudstor in data folder (although many are ones Shirley had already
uploaded, there are additional, eg Hong Kong).
I'm pretty sure I didn't add the input files, as I only actually edited the
git repository online manually.

Apologies for the mix-up, however it occurred, but you only need to add the
analysis folder and those two files I believe (at least in terms of my
edits to Shirley's code - should be only diff)

I'll be back online on Monday

Cheers

Carl

**Comment by carlhiggs** [comment]
I think I see what's happening; this pr is intended for Shirley's GTFS
branch, not master - apologies if the final pr was made to incorrect branch
(seems logical occurrence).

My code differs to Shirley's in that it didn't refer to gtfs files with in
analysis folder, only within data folder, and these are to be downloaded
from data subfolder on cloudstor.  I'll confirm on Monday that all uploaded
correctly, however the final gpkg for others to check/use is there.

Hope mystery solved!

**Comment by gboeing** [comment]
Interesting... so the diff isn't showing your branch vs Shirley's then... it must be showing your branch vs the upstream (mine)?

Shirley, we should chat about this in your PR upstream, but see my comment to Carl above in this thread about the diff size and all the data being stored in it here.

**Comment by carlhiggs** [comment]
Hi all, just catching up with e-mails etc since Friday --- as per discussion earlier, in rush to get things done on Thursday, I put this PR request against 'master' instead of 'GTFS', so i'll close this and re-do PR against the GTFS branch.

**Comment by carlhiggs** [comment]
@shiqin-liu @gboeing For reference, the correct and current pull request is [here](https://github.com/shiqin-liu/global-indicators/pull/8); thanks!

**Pull request closed without merging**
